# Makefile to compile nanopond.c

CC=gcc
CFLAGS=-O6 -march=athlon-mp -mtune=athlon-mp -mmmx -msse -fomit-frame-pointer -ftree-vectorize -funroll-loops -fstrength-reduce -Wall -pipe -s

all:
	$(CC) $(CFLAGS) -o nanopond-mv nanopond-mv.c -lSDL

clean:
	rm -f nanopond-mv nanopond-mv.gc??
